version: '3.8'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: qi-streaming-redpanda
    command:
      - redpanda
      - start
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://localhost:9092
      - --pandaproxy-addr=PLAINTEXT://0.0.0.0:8082
      - --advertise-pandaproxy-addr=PLAINTEXT://localhost:8082
      - --schema-registry-addr=PLAINTEXT://0.0.0.0:8081
      - --rpc-addr=PLAINTEXT://0.0.0.0:33145
      - --advertise-rpc-addr=PLAINTEXT://localhost:33145
      - --mode=dev-container
      - --smp=1
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
    ports:
      - "8081:8081"    # Schema Registry
      - "8082:8082"    # Pandaproxy (REST API)
      - "9092:9092"    # Kafka
      - "9644:9644"    # Admin API
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - streaming-network
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  # Optional: Redpanda Console for Web UI
  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: qi-streaming-console
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - "8080:8080"
    networks:
      - streaming-network
    depends_on:
      redpanda:
        condition: service_healthy

  # Optional: Schema Registry UI
  schema-registry-ui:
    image: landoop/schema-registry-ui:latest
    container_name: qi-streaming-schema-ui
    environment:
      SCHEMAREGISTRY_URL: http://redpanda:8081
      PROXY: "true"
    ports:
      - "8001:8000"
    networks:
      - streaming-network
    depends_on:
      redpanda:
        condition: service_healthy

volumes:
  redpanda-data:
    name: qi-streaming-data

networks:
  streaming-network:
    name: qi-streaming-net
    driver: bridge